<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Version>1.1.0</Version>
        <Authors>Frends</Authors>
        <Copyright>Frends</Copyright>
        <Company>Frends</Company>
        <Product>Frends</Product>
        <PackageTags>Frends</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>Frends task for converting X12 documents to JSON</Description>
        <PackageProjectUrl>https://frends.com/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/FrendsPlatform/Frends.X12/tree/main/Frends.X12.ConvertToJson</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="EdiFabric" Version="10.4.2" />
        <PackageReference Include="Frends.Edifabric.Activation" Version="1.0.3" />
        <PackageReference Include="Frends.Edifabric.Templates.X12" Version="1.0.2" />
        <PackageReference Include="FrendsTaskAnalyzers" Version="1.9.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="FrendsTaskMetadata.json" Pack="true" PackagePath="/">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </AdditionalFiles>
        <Content Include="migration.json" PackagePath="/" Pack="true" />
        <Content Include="../CHANGELOG.md" PackagePath="/" Pack="true" />
    </ItemGroup>

</Project>
